Sprint 5
microservices-course-itmo/notification-service pull request #13
Opened 2020-10-27 15:23 UTC by TheOneTwelfth

2020-11-04 16:46 UTC, shinehlina requested changes

2020-11-04 16:46 UTC, shinehlina commented on src/main/java/com/wine/to/up/notification/service/mobile/apns/ApnsService.java
> +        log.info("Sending notification to device: " + request.getDeviceToken());
log.info("Sending notification to device: {}", request.getDeviceToken());

2020-11-04 16:46 UTC, shinehlina commented on src/main/java/com/wine/to/up/notification/service/mobile/apns/ApnsService.java
> +        log.info("Sending notification to device: " + request.getDeviceToken());
Странно, сонар на такое обычно ругается

2020-11-04 16:46 UTC, shinehlina commented on src/test/java/com/wine/to/up/notification/service/domain/entity/MessageTest.java
> +        assertThat(message.getContent()).isEqualTo(content);
Это тестирование сеттера? Это вообще можно было заигнорить у сонара

2020-11-04 16:46 UTC, shinehlina commented on pom.xml
> +
И еще версию своего приложения поднимите)

2020-11-08 14:51 UTC, AfanasievYuriy approved these changes
проверьте версии апишек каталога и комон

2020-11-08 14:51 UTC, AfanasievYuriy commented on pom.xml
>          <service.commonlib.version>0.2.1-SNAPSHOT</service.commonlib.version>
это последняя версия?

2020-11-08 14:51 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/notification/service/mobile/fcm/FcmInitializer.java
> +                    ).setDatabaseUrl("https://wineup-android.firebaseio.com")
давайте в константы такое выносить

2020-11-09 13:31 UTC, merged