Task/user service listener
microservices-course-itmo/notification-service pull request #14
Opened 2020-11-02 14:17 UTC by TNX2021

2020-11-02 14:23 UTC, TheOneTwelfth commented on src/main/java/com/wine/to/up/user/service/api/UserServiceApiProperties.java
> +package com.wine.to.up.user.service.api;
Это нужно импортировать из API user-service

2020-11-02 14:23 UTC, TheOneTwelfth commented on src/main/java/com/wine/to/up/user/service/api/dto/UserTokens.java
> +package com.wine.to.up.user.service.api.dto;
и это

2020-11-02 14:23 UTC, TheOneTwelfth commented on src/main/java/com/wine/to/up/user/service/api/dto/WineResponse.java
> +package com.wine.to.up.user.service.api.dto;
И это тоже

2020-11-05 14:08 UTC, TheOneTwelfth requested changes

2020-11-05 14:08 UTC, TheOneTwelfth commented on src/main/java/com/wine/to/up/notification/service/messaging/UserServiceKafkaMessageHandler.java
> +                        apnsService.sendMessage(new ApnsPushNotificationRequest(token, "default", "payload"));
Доставай wineName и newWinePrice из wineResponse и пиши какое-нибудь форматированное сообщение по типу "Появилась скидка на <wineName>! Новая цена: <newWinePrice>"

2020-11-05 14:08 UTC, TheOneTwelfth commented on src/main/java/com/wine/to/up/notification/service/messaging/UserServiceKafkaMessageHandler.java
> +                        fcmService.sendMessage(new FcmPushNotificationRequest("title", "message", token));
Здесь то же самое

2020-11-06 08:12 UTC, TNX2021 commented on src/main/java/com/wine/to/up/notification/service/messaging/UserServiceKafkaMessageHandler.java
> +                        apnsService.sendMessage(new ApnsPushNotificationRequest(token, "default", "payload"));
"пиши сообщение" имеется в виду логирование? Или payload в sendMessage?

2020-11-06 16:41 UTC, TheOneTwelfth approved these changes

2020-11-06 16:42 UTC, merged