Sprint 8
microservices-course-itmo/notification-service pull request #24
Opened 2020-11-17 15:24 UTC by TheOneTwelfth

2020-11-23 12:01 UTC, shinehlina requested changes

2020-11-23 12:01 UTC, shinehlina commented on pom.xml
>          <service.firebase.version>6.8.1</service.firebase.version>
Версию самого приложения

2020-11-23 12:01 UTC, shinehlina commented on pom.xml
> +            <version>${springfox-swagger2.version}</version>
Что будет, если не указывать версию? Ее нет в паренте?

2020-11-23 12:01 UTC, shinehlina commented on pom.xml
> +            <version>${springfox-swagger-ui.version}</version>
И здесь

2020-11-23 12:01 UTC, shinehlina commented on src/main/java/com/wine/to/up/notification/service/controller/NotificationController.java
> +        log.debug("New notification CRUD request. Action = UPDATE. id = {}",notification.getId());
Нажмите ctrl + alt + L. Пробелы пропущены

2020-11-28 15:11 UTC, TheOneTwelfth commented on pom.xml
> +            <version>${springfox-swagger2.version}</version>
Будет `Project build error: version is missing`

2020-11-29 20:09 UTC, shinehlina commented on pom.xml
> +            <version>${springfox-swagger2.version}</version>
Не, я была не права, там есть вся эта зависимость https://github.com/microservices-course-itmo/wine-app-parent/blob/dev/pom.xml Можно всю зависимость убрать

2020-11-29 20:11 UTC, shinehlina approved these changes
Лишние зависимости все равно уберите)

2020-11-29 20:11 UTC, shinehlina commented on pom.xml
> +            <version>${springfox-swagger-ui.version}</version>
Вот эта тоже полностью не нужна

2020-12-04 19:02 UTC, merged