Make ios tests compatible with new logic
microservices-course-itmo/notification-service pull request #45
Opened 2021-03-23 23:28 UTC by 3LITA

2021-03-23 23:43 UTC, TheOneTwelfth commented
Выглядит ок, но давай допишем скрипт запуска тестов, в котором будут проставляться переменные среды, а то без `APNS_P8_DECRYPT_PASSWORD` тесты падают

2021-03-23 23:44 UTC, TheOneTwelfth requested changes
Выглядит ок, но давай допишем скрипт запуска тестов, в котором будут проставляться переменные среды, а то без `APNS_P8_DECRYPT_PASSWORD` тесты падают.

2021-03-23 23:44 UTC, TheOneTwelfth commented
> Выглядит ок, но давай допишем скрипт запуска тестов, в котором будут проставляться переменные среды, а то без `APNS_P8_DECRYPT_PASSWORD` тесты падают.

И скрипт запуска приложения заодно, тоже с переменными

2021-03-23 23:49 UTC, 3LITA commented
> > Выглядит ок, но давай допишем скрипт запуска тестов, в котором будут проставляться переменные среды, а то без `APNS_P8_DECRYPT_PASSWORD` тесты падают.
> 
> И скрипт запуска приложения заодно, тоже с переменными

Если мы сделаем такой скрипт, то пропалим в нем все наши переменные окружения, предлагаю создать файл с перечислением переменных, типа `.env`, разослать его всей команде, и будем его вызывать в этом скрипте

2021-03-24 01:19 UTC, TheOneTwelfth requested changes

2021-03-24 01:19 UTC, TheOneTwelfth commented on run.sh
> +docker-compose -f profiles/minimal-Infrastructure.yml up
`up -d`, иначе оно повиснет в шелле и не перейдет к следующему этапу

2021-03-24 01:19 UTC, TheOneTwelfth commented on test.sh
> +mvn clean install
`mvn clean install -s settings.xml`

2021-03-24 06:09 UTC, Kot1que approved these changes

2021-03-24 06:09 UTC, Kot1que commented on src/test/java/com/wine/to/up/notification/service/mobile/apns/ApnsTest.java
> +        public void handlePushNotificationRejected(io.netty.handler.codec.http2.Http2Headers http2Headers, io.netty.buffer.ByteBuf byteBuf, RejectionReason rejectionReason, Instant instant) {
полные пути до классов, наверное, можно на импорты поменять. здесь из-за этого строка слишком длинная

2021-03-24 06:09 UTC, Kot1que commented on src/test/java/com/wine/to/up/notification/service/mobile/apns/ApnsTest.java
> +        public void handlePushNotificationRejected(io.netty.handler.codec.http2.Http2Headers http2Headers, io.netty.buffer.ByteBuf byteBuf, RejectionReason rejectionReason, Instant instant) {
если там конфликты, то ок, я не пуллил код

2021-03-24 07:07 UTC, Kot1que approved these changes

2021-03-24 14:14 UTC, TheOneTwelfth approved these changes

2021-03-24 15:01 UTC, merged