Sprint 2
microservices-course-itmo/notification-service pull request #9
Opened 2020-10-13 10:09 UTC by TheOneTwelfth

2020-10-13 10:11 UTC, TheOneTwelfth commented on src/main/java/com/wine/to/up/notification/service/configuration/KafkaConfiguration.java
> +                                                                            NotificationServiceApiProperties notificationServiceApiProperties,
Здесь пока заглушка, т.к. у Catalog Service еще нет API

2020-10-13 19:41 UTC, shinehlina commented
Если это тот спринт, что закончился 13, то переименуйте в 3)

2020-10-13 19:57 UTC, shinehlina requested changes
В целом выглядит красиво. Возможно, вам часть документации, которая про совсем детали лучше в javadoc положить

2020-10-13 19:57 UTC, shinehlina commented on src/main/java/com/wine/to/up/notification/service/service/fcm/FcmService.java
> +    public void sendMessage(FcmPushNotificationRequest request)
Можете это в интерфейс параметрезированный вынести

2020-10-13 19:57 UTC, shinehlina commented on src/main/java/com/wine/to/up/notification/service/service/fcm/FcmService.java
> +            throws InterruptedException, ExecutionException {
И я правильно понимаю, что вы это нигде пока не вызываете?

2020-10-13 19:57 UTC, shinehlina commented on src/main/resources/application.properties
> +apns.key-file=${APNS_KEY_FILE:filename}
Добавьте комментарии (можете в и самом ApnsSettings тоже). Для меня не очень понятны эти дефолтные значения, они временные?

2020-10-13 19:57 UTC, shinehlina commented on pom.xml
> +        <!-- Required: Firebase-->
Ну и версию приложения ап

2020-10-13 19:57 UTC, shinehlina commented on src/main/java/com/wine/to/up/notification/service/service/apns/ApnsService.java
> +            return null;
В другом сервисе вы их бросаете наверх. Может, здесь также стоит сделать?
null не оч красиво возвращать

 public void sendMessage(FcmPushNotificationRequest request)
            throws InterruptedException, ExecutionException {

2020-10-13 20:01 UTC, shinehlina commented
И если это все-таки pr за 3 спринт, то сделайте все, что нужно для подготовки к деплою из general.

2020-10-15 19:28 UTC, heisen1berg commented on src/main/java/com/wine/to/up/notification/service/service/fcm/FcmService.java
> +            throws InterruptedException, ExecutionException {
будет вызываться из кафки, но так как кафка пока нерабочая, из-за отсутствия апи каталог сервиса, то, да, пока нигде не вызывается

2020-10-17 17:10 UTC, AfanasievYuriy requested changes

2020-10-17 17:10 UTC, AfanasievYuriy commented on pom.xml
> +            <version>6.8.1</version>
в проперти вынесите

2020-10-17 17:10 UTC, AfanasievYuriy commented on pom.xml
> +            <version>0.14.1</version>
проперти

2020-10-17 17:10 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/notification/service/messaging/CatalogKafkaMessageHandler.java
> +            ex.printStackTrace();
стектрейс печатайте в логе тогда уже

2020-10-17 17:10 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/notification/service/mobile/apns/ApnsService.java
> +//@Service
удолите

2020-10-17 17:10 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/notification/service/mobile/apns/ApnsSettings.java
> +//@Component
удолите

2020-10-17 17:10 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/notification/service/mobile/fcm/FcmInitializer.java
> +@Service
джавадок в классу напишите плз

2020-10-17 17:10 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/notification/service/mobile/fcm/FcmInitializer.java
> +@Service
ко всем специфик классам (где фигурирует fcm в названии)

2020-10-17 17:10 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/notification/service/mobile/apns/ApnsService.java
> +//@Service
кстати? а почему он не @сервис то?

2020-10-17 17:10 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/notification/service/mobile/fcm/FcmService.java
> +public class FcmService implements NotificationSender<FcmPushNotificationRequest> {
док

2020-10-17 18:05 UTC, TheOneTwelfth commented on src/main/java/com/wine/to/up/notification/service/mobile/apns/ApnsService.java
> +//@Service
Это у @heisen1berg надо спросить, он должен быть сервисом

2020-10-17 18:05 UTC, TheOneTwelfth commented on src/main/java/com/wine/to/up/notification/service/mobile/apns/ApnsSettings.java
> +//@Component
То же, что и сверху

2020-10-19 20:21 UTC, AfanasievYuriy approved these changes

2020-10-19 20:21 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/notification/service/domain/model/apns/ApnsPushNotificationRequest.java
> + */
я думал поразвернутее напишите :)

сам док на всеми аннотациями ставится

2020-10-19 20:21 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/notification/service/mobile/apns/ApnsService.java
> +     * @see com.wine.to.up.notification.service.domain.model.apns.ApnsPushNotificationRequest
в доке тоже можно импорты делать (чтобы на полное имя класса не смотреть)

2020-10-19 20:21 UTC, AfanasievYuriy commented on src/main/java/com/wine/to/up/notification/service/mobile/fcm/FcmInitializer.java
> + */
над аннотациями

2020-10-20 16:13 UTC, shinehlina approved these changes

2020-10-20 16:34 UTC, merged